name: ARM test
on: push

jobs:
  build:
    name: Main build
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Run build script
      working-directory: scripts
      run: docker run --privileged --rm tonistiigi/binfmt --install amd64
